export const GET_CHANNELS_SUCCESS = "GET_CHANNELS";
export const GET_PROGRAMS_SUCCESS = "GET_PROGRAMS";
export const GET_PROGRAMS_REQUESTED = "GET_PROGRAMS_REQUESTED";
export const GET_CHANNELS_REQUESTED = "GET_CHANNELS_REQUESTED";